spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    driver-class-name: org.postgresql.Driver
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        connection:
          autocommit: false
        format_sql: true

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

server:
  port: 8080

